=== amunroe1/CSE598-Munroe/Hotels.xsd
<?xml version="1.0"?>
<xs:xschema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Hotels">
    <xs:complexType>
      <xs:element name="Hotel" maxOccurs="unbounded">
        <xs:attribute name="Rating" type="xs:decimal"/>
        <xs:complexType>
          <xs:sequence>
            
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Phone" type="xs:string" maxOccurs="unbounded"/>
            
            <xs:element name="Address">
              <xs:attribute name="NearestAirport" type = "xs:string" use="required"/>
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="Number" type="xs:integer"/>
                  <xs:element name="City" type="xs:string"/>
                  <xs:element name="State" type"xs:string"/>
                  <xs:element name="Zip" type"xs:integer"/>
                </xs:sequence>
              </xs:complexType>
              
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:complexType>
  </xs:element>
</xs:xschema>

=== amunroe1/CSE598-Munroe/Assignment_4/Hotels.xml
<?xml version="1.0" encoding="utf-8"?>
<Hotels xmlns="http://www.hotel.com/hotel-schema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.hotel.com/hotel-schema https://raw.githubusercontent.com/amunroe1/CSE598-Munroe/main/Assignment_4/Hotels.xsd">
	<Hotel Rating="4.2">
		<Name>Westin</Name>
		<Phone>480-968-8885</Phone>
		<Phone>800-937-8461</Phone>
		<Address NearestAirport="Sky Harbor">
			<Number>11</Number>
			<Street>E. 7th St</Street>
			<City>Tempe</City>
			<State>Arizona</State>
			<Zip>85281</Zip>
		</Address>
	</Hotel>
	<Hotel>
		<Name>Omni Tempe Hotel</Name>
		<Phone>602-794-8600</Phone>
		<Address NearestAirport="Sky Harbor">
			<Number>7</Number>
			<Street>E. University Dr.</Street>
			<City>Tempe</City>
			<State>Arizona</State>
			<Zip>85281</Zip>
		</Address>
	</Hotel>
	<Hotel>
		<Name>Comfort Inn</Name>
		<Phone>(480) 858-9898</Phone>
		<Address NearestAirport="Sky Harbor">
			<Number>808</Number>
			<Street>N. Scottsdale Rd.</Street>
			<City>Tempe</City>
			<State>Arizona</State>
			<Zip>85281</Zip>
		</Address>
	</Hotel>
	<Hotel Rating="4.0">
		<Name>Best Western</Name>
		<Phone>888-389-4121</Phone>
		<Address NearestAirport="Bradley International">
			<Number>185</Number>
			<Street>Brainard Rd.</Street>
			<City>Hartford</City>
			<State>CT</State>
			<Zip>06114</Zip>
		</Address>
	</Hotel>
	<Hotel Rating="4.0">
		<Name>Mariott</Name>
		<Phone>800-716-8490</Phone>
		<Address NearestAirport="Bradley International">
			<Number>20006103</Number>
			<Street>Columbus Blvd.</Street>
			<City>Hartford</City>
			<State>CT</State>
			<Zip>06103</Zip>
		</Address>
	</Hotel>
	<Hotel Rating="4.0">
		<Name>Hampton Inn</Name>
		<Phone>800-805-5223</Phone>
		<Address NearestAirport="Bradley International">
			<Number>351</Number>
			<Street>Pitkin St.</Street>
			<City>East Hartford</City>
			<State>CT</State>
			<Zip>06108</Zip>
		</Address>
	</Hotel>
	<Hotel Rating="2.0">
		<Name>Economy Inn</Name>
		<Phone>888-965-1860</Phone>
		<Address NearestAirport="Bradley International">
			<Number>490</Number>
			<Street>Main St.</Street>
			<City>East Hartford</City>
			<State>CT</State>
			<Zip>06108</Zip>
		</Address>
	</Hotel>
	<Hotel Rating="4.0">
		<Name>Hyatt Place</Name>
		<Phone>800-805-5223</Phone>
		<Address NearestAirport="Boston Logan">
			<Number>295</Number>
			<Street>Northern Ave.</Street>
			<City>Boston</City>
			<State>MA</State>
			<Zip>02210</Zip>
		</Address>
	</Hotel>
	<Hotel Rating="4.0">
		<Name>Seaport Hotel</Name>
		<Phone>888-788-5576</Phone>
		<Address NearestAirport="Boston Logan">
			<Number>1</Number>
			<Street>Seaport Ln.</Street>
			<City>Boston</City>
			<State>MA</State>
			<Zip>02210</Zip>
		</Address>
	</Hotel>
	<Hotel Rating="4.0">
		<Name>Residence Inn</Name>
		<Phone>888-965-8297</Phone>
		<Address NearestAirport="Boston Logan">
			<Number>370</Number>
			<Street>Congress St.</Street>
			<City>Boston</City>
			<State>MA</State>
			<Zip>02210</Zip>
		</Address>
	</Hotel>
</Hotels>
